# Generated by Django 3.0.6 on 2020-05-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0003_skill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='key',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='key',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
