# Generated by Django 3.0.6 on 2020-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0004_auto_20200510_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
